### ISSUE TITLE
Needs to be able to handle multiple implementations

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/FluffySpoon.JavaScript.CSharpParser#3]
Right now, `inheritsFrom` on a `CSharpClass` or `CSharpInterface` only returns one `CSharpType`, which is not correct.

**Comment by SharpSeeEr** [comment]
+1 for this issue.  I have a class that inherits from 3 interfaces, but the parser ignored the entire class because it didn't match the regex on line 42 of `ClassParser.ts`.  I've been playing around with the regex to try to get it to match `public class MyClass : IInterface1, IInterface2` so the comma delimited list of interfaces/classes is set as the `inheritsFrom` to no avail.  That is one doozy of a regex.  :)  Of course `inheritsFrom` needs to be changed to an array as well.  

I'm willing to make all these changes and submit a pull request, I just may need some additional help with the RegEx.

**Comment by ffMathy** [comment]
I typically use regex101.com for this kind of stuff. Put the string in there, and put some code in as an example.

Then make a new test which demonstrates your case, and have all tests pass.

Does that help?

**Comment by SharpSeeEr** [comment]
Awesome!  I've been using regex101.com to figure it out!  No luck so far.  I'll keep looking into it.

**Comment by ffMathy** [comment]
I'm currently fixing this as we speak. Sorry for the delay.

**Comment by ffMathy** [comment]
This has now been fixed.
